global:
  scrape_interval: 5s # 기본 수집 주기

scrape_configs:
  - job_name: 'admin'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['admin:8081']

  - job_name: 'gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gateway:8080']

  - job_name: 'collector'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['collector:8090']

  - job_name: 'consumer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'consumer:8091' ]

  - job_name: 'rabbitmq'
    static_configs:
      - targets: [ 'rabbitmq-exporter:9419' ]

  - job_name: 'jmeter'
    static_configs:
      - targets: [ 'host.docker.internal:9270' ]
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: instance
        regex: '(.*):9270'
        replacement: '$1-jmeter'
