spring:
  cloud:
    gateway:
      routes:
        - id: collector
          uri: http://collector.ckt:8090
          predicates:
            - Path=/api/v1/vehicles/collector/**, /api/v1/sse/**

        - id: admin
          uri: http://admin.ckt:8081
          predicates:
            - Path=/api/v1/auth/**, /api/v1/companies/**, /api/v1/customers/**, /api/v1/vehicles/**, /api/v1/rentals/**, /api/v1/logs/**, /api/v1/tracking/**

cors:
  allowed-origins: https://ckt.services
