server:
  port: 8081

spring:
  application:
    name: admin

  datasource:
    url: jdbc:postgresql://${DB_URL}:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: false
    open-in-view: false
    properties.hibernate:
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategySnakeCaseImpl
      default_batch_fetch_size: 1000
      globally_quoted_identifiers: false
