server:
  port: ${SERVER_PORT}

spring:
  application:
    name: collector

  datasource:
    url: jdbc:mysql://${DB_URL}:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: false
    open-in-view: false
    properties.hibernate:
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategySnakeCaseImpl
      default_batch_fetch_size: 1000
      globally_quoted_identifiers: false
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}
    addresses: amqp://${SPRING_RABBITMQ_HOST}:${SPRING_RABBITMQ_PORT}
    virtual-host: /

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  prometheus:
    metrics:
      export:
        enabled: true
